version: '3.7'
services:
  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3308:3306'
    healthcheck:
      test: ["CMD", "bash", "-c", "/usr/bin/mysql --user=root --execute \"SHOW DATABASES;\""]
      interval: 3s
      timeout: 1s
      retries: 5
